title: Watchmaking
description: "A watchmaking student's resource, study guide and blog."

about-blog: "The purpose of this student blog is to document the time spent studying the two-year *WOSTEP 3'000-hour Program* at a watchmaking school in Europe. The course began in January 2021."

disclaimers:
  views-and-opinions: "Any views or opinions represented on this website are personal and belong solely to the website owner and do not represent those of people, institutions or organizations that the owner may or may not be associated with in professional or personal capacity."
  fair-use: "This site and the content made available through this site are for educational and informational purposes only.<br><br>The site may contain copyrighted material owned by a third party, the use of which has not always been specifically authorized by the copyright owner. Notwithstanding a copyright owner’s rights under the Copyright Act, Section 107 of the Copyright Act allows limited use of copyrighted material without requiring permission from the rights holders, for purposes such as education, criticism, comment, news reporting, teaching, scholarship, and research. These so-called “fair uses” are permitted even if the use of the work would otherwise be infringing.<br><br>If you wish to use copyrighted material published on this site for your own purposes that go beyond fair use, you must obtain permission from the copyright owner.<br><br>If you believe that any content or postings on this site violates your intellectual property or other rights, please get in contact at *[tizi38bei@relay.firefox.com](mailto:tizi38bei@relay.firefox.com)*."
  external-links: "Throughout the site you will find links to external websites, marked with a <a target='_blank'></a> icon. Although every effort is made to ensure these links are accurate, up to date and relevant, we cannot take responsibility for pages maintained by external providers."

keywords: watchmaking,horology,time,student,study,learn,school,course,hobby,history,terms,tools,techniques,resources,references,education,exam,wiki,definition,index,bibliography,books,guides,videography,videos
author: watchmaking.xyz
logo: /favicon-256x256.png

permalink: /student-blog/:title

collections:
  guides:
    output: true
    permalink: /guides/:title

baseurl: ""
url: "https://watchmaking.xyz"

destination: docs

sass:
    sass_dir: _sass
    style: compressed

jekyll-minifier:
  compress_javascript: false
  uglifier_args:
    harmony: true

plugins:
  - jekyll-include-cache
  - jekyll-last-modified-at
  - jekyll-sitemap
  - jekyll-target-blank
  - jekyll-loading-lazy
  - jekyll-minifier

exclude:
  - .jekyll-cache
  - deploy.sh

defaults:
  -
    scope:
      path: "downloads/*.pdf"
    values:
      sitemap: false

target-blank:
   noreferrer: false
